
version: 2

models:

  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: sales
    description: "One record per employees "
    columns:
      - name: first_name
        tests:
          - string_not_empty

  - name: finale
    description: "Finale table contains all information of employees"
    columns: 
      - name: genre
        tests:
          - string_not_empty

      - name: id
        tests:
          - unique
          - not_null   
  
  - name: sales_per_dpt
    description: "salary groups per department"
    columns: 
      - name: department
        tests:
          - accepted_values:
             values: ['Operations','Informatique', 'Finance','comptable','Engineering','HR']
          - string_not_empty